name: Test
on: [push]
jobs:
  build:
    strategy:
      max-parallel: 6
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: [7.2, 7.3]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up php and composer
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: 'mbstring, xdebug'
      - name: Check PHP and Composer Version 
        run: php -v && composer -V
      .... Add more steps to install dependencies and then test
