#測試 8
image: 
  name: gitlab/gitlab-runner:latest
  entrypoint: [""]

stages:
    - Test
    - Deploy QA
    - Deploy Production
    - Message

Test:
    stage: Test
    script:
        - echo "Pass Test"
    only:
        - qa
        - release
    tags:
        - qa
        - release

Deploy QA:
    stage: Deploy QA
    script:
        - echo "Run Deploy QA"
        - pwd
        - cd /datadisk/gitlab-nfs/qa/chat.gvm.com.tw
        - git checkout qa
        - git fetch --all
        - git reset --hard origin/qa
        - git pull origin qa
    only:
        - qa
    tags:
        - qa
    # when: manual
    environment: test

Deploy Production:
    stage: Deploy Production
    script:
        - echo "Run Deploy Production"
        - pwd
        - cd /datadisk/gitlab-nfs/release/chat.gvm.com.tw
        - git checkout qa
        - git fetch --all
        - git reset --hard origin/qa
        - git pull origin qa
    only:
        - release
    tags:
        - release
    # when: manual
    environment: Production

Message:
    stage: Message
    script:
        - echo "Message"
    only:
        - qa
        - release
    tags:
        - qa
        - release
